import React from "react";
import { Container } from "react-bootstrap";

const Index = () => {
  return (
    <div className="environmental-policy">
      <Container>
        <h1 className="policies-title" style={{ textAlign: "center" }}>
          Environmental Policy
        </h1>
        <h6 style={{ textAlign: "center", marginTop: "15px" }}>
          Nomadic Tribe is committed to responsible and environmentally
          sustainable tourism, following the 17 Sustainable Development Goals
          adopted by the UN, targeting more specifically Goal 13 “Take urgent
          action to combat climate change and its impacts”.
        </h6>
        <h6 style={{ textAlign: "center", marginTop: "15px" }}>
          Nomadic Tribe upholds that Indigenous Peoples manage a third of global
          forests and they are the leading stewards of our environment. Their
          role is fundamental in the global curbing of gas emissions and they
          protect around 80% of the world’s biodiversity, however they are the
          first victims of climate change. Therefore it is imperative for
          Nomadic Tribe to act on climate change and reduce the carbon emissions
          generated by our company and our travellers to further protect
          Indigenous Peoples, their Ecosystems and Traditional Knowledge.
        </h6>
        <div style={{ marginTop: "50px" }}>
          <h3 style={{ fontWeight: "600" }}>Our commitment</h3>
          <h6 style={{ marginTop: "10px" }}>
            Our travels are designed to respect the values of responsible
            tourism and sustainable development. We commit to become a carbon
            neutral Company, fighting against climate change. We intend to
            reduce our emissions through ecological strategies, maintaining our
            carbon neutrality by reducing and seeking less carbon-intensive
            solutions.
          </h6>
        </div>
        <div style={{ marginTop: "50px" }}>
          <h3 style={{ fontWeight: "600" }}>Responsibility and partnerships</h3>
          <h6 style={{ marginTop: "10px" }}>
            We partner with organizations that support and follow our values and
            we commit to communicate our environmental objectives to all our
            external stakeholders. We endorse the work of all organizations
            working in environmental protection and sustainable development. We
            joined Tourism Declares in 2020 along with other businesses,
            organisations and individuals in the tourism sector, with the intent
            to come together to prevent climate change.
          </h6>
        </div>
        <div style={{ marginTop: "50px" }}>
          <h3 style={{ fontWeight: "600" }}>Policy aims / “Ways to do it”</h3>
          <h6 style={{ marginTop: "10px" }}>
            We endeavour to monitor our progress and review all our
            environmental performances annually, keeping our environmental
            policy up to date. We agree to commit to environmental principles
            and to bring improvements along the way, incorporating environmental
            considerations into business decisions. We will compensate the
            emissions created by our travellers through ‘offsets’ tangible
            projects carried out by our Foundation. The Environmental
            preservation is not only one of the main pursuits of our Foundation,
            but also one of the fundamental pillars of its Sustainable Business
            Model.
          </h6>
        </div>
        <div style={{ marginTop: "50px" }}>
          <h3 style={{ fontWeight: "600" }}>
            Criteria for the selection of our tour operators
          </h3>
          <h6 style={{ marginTop: "10px" }}>
            At Nomadic Tribe we expect similar environmental standards from all
            our tour operators and we intend to implement responsible business
            practices. In every destination we visit our aim is to work towards
            the preservation of the natural environment and reduce our negative
            impact caused by our tours. To do this, we choose to work with
            partners who strive to offer lower-impact in destination travel,
            locally owned and run accommodation and prefer to use restaurants
            where the ingredients have been sourced locally, to reduce the food
            miles and overall carbon impact.
          </h6>
        </div>
        <div style={{ marginTop: "50px" }}>
          <h3 style={{ fontWeight: "600" }}>Advocacy</h3>
          <h6 style={{ marginTop: "10px" }}>
            We believe in the power of education; we are committed to raising
            awareness about climate change and sustainability to further open
            discussions on the topic, generating purposeful critical thinking
            and supporting sustainable environmental actions. We intend to use
            our platforms to dispense honest, unfiltered and authentic
            information on waste management, water and energy consumption, local
            economy support and wildlife preservation. We commit to educate our
            travellers, tour operators, stakeholders and ourselves on
            environmental matters. Ultimately, at Nomadic Tribe we pledge to
            strive for Environmental Justice and Decolonized Conservation.
          </h6>
        </div>
      </Container>
    </div>
  );
};

export default Index;
